/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotal.man;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author HCL
 */
public class newbooking extends javax.swing.JFrame {

    /**
     * Creates new form newbooking
     */
    public newbooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_male = new javax.swing.JRadioButton();
        rb_female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tf_persons = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_mobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rb_ac = new javax.swing.JRadioButton();
        rb_nac = new javax.swing.JRadioButton();
        rb_d = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_checkin = new javax.swing.JTextField();
        tf_checkout = new javax.swing.JTextField();
        cb_rooms = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_security = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("MALE");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("FEMALE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("NEW BOOKING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 11, 166, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CUSTOMER DETAIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 173, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 53, 34));

        tf_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 119, 127, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("AGE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 117, 35, 36));

        tf_age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tf_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 118, 60, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("GENDER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 117, 57, 37));

        buttonGroup1.add(rb_male);
        rb_male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_male.setText("MALE");
        getContentPane().add(rb_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        buttonGroup1.add(rb_female);
        rb_female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_female.setText("FEMALE");
        getContentPane().add(rb_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 102, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("NUMBER OF PERSON");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, 34));

        tf_persons.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tf_persons, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 199, 54, 34));

        jLabel7.setText("MOBILE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 201, 58, 32));

        tf_mobile.setToolTipText("REMEMBER IT\n");
        getContentPane().add(tf_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 201, 141, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("BOOKING DETAIL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, 175, 31));

        jLabel9.setText("ROOM TYPE :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 28));

        buttonGroup3.add(rb_ac);
        rb_ac.setText("A.C");
        getContentPane().add(rb_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 313, -1, -1));

        buttonGroup3.add(rb_nac);
        rb_nac.setText("NON A.C");
        getContentPane().add(rb_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 313, -1, -1));

        buttonGroup3.add(rb_d);
        rb_d.setText("DELUX");
        getContentPane().add(rb_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 313, 85, -1));

        jLabel10.setText("CHECK-IN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 362, 65, 39));

        jLabel11.setText("CHECK-OUT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 366, 98, 30));
        getContentPane().add(tf_checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 366, 130, 30));

        tf_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_checkoutActionPerformed(evt);
            }
        });
        getContentPane().add(tf_checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 366, 130, 30));

        cb_rooms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", " " }));
        getContentPane().add(cb_rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 431, 49, -1));

        jLabel12.setText("NO OF ROOMS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 434, -1, -1));

        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 492, 86, 36));

        jButton2.setText("MAKE BOOKING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 492, -1, 36));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 492, 104, 36));

        jLabel13.setText("SECURITY PAYMENT");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 428, -1, 27));
        getContentPane().add(tf_security, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 428, 110, 27));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\HCL\\Videos\\Capture.PNG")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_checkoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_checkoutActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String name, age, gender="", persons, mobile, roomtype="", rooms, checkin, checkout,sec;
name=tf_name.getText();
age=tf_age.getText();
if(rb_female.isSelected())
{gender="Male";}
else if(rb_female.isSelected())
{gender="Female";}
persons=tf_persons.getText();
mobile=tf_mobile.getText();
{
If(rb_nac.isSelected()); 
{roomtype="Non-AC";}
}
if(rb_ac.isSelected())
{roomtype="AC";}
else if(rb_d.isSelected())
{roomtype="Deluxe";}
rooms=(String)cb_rooms.getSelectedItem();
checkin=tf_checkin.getText();
checkout=tf_checkout.getText();
sec=tf_security.getText();
if(name.isEmpty())
{
JOptionPane.showMessageDialog(null, "Name field can't be left empty");
} 
else if(age.isEmpty())
{
JOptionPane.showMessageDialog(null, "Age field can't be left empty");
} else if(gender.isEmpty())
{
JOptionPane.showMessageDialog(null, "Select a gender type");
} else if(persons.isEmpty()){
JOptionPane.showMessageDialog(null, "Numbers of person field can't be left empty");
}
else if(mobile.isEmpty())
{
JOptionPane.showMessageDialog(null, "Mobile field can't be left empty");
} else if(roomtype.isEmpty())
{
JOptionPane.showMessageDialog(null, "Room type is not selected");
} else if(checkin.isEmpty())
{
JOptionPane.showMessageDialog(null, "Please provide check-in date");
} else if(checkout.isEmpty())
{
JOptionPane.showMessageDialog(null, "The check-out date can't be left empty");
} else if(checkin.equals(checkout))
{
JOptionPane.showMessageDialog(null, "Check-in and check-out dates can't be same");
}
 else if(sec.isEmpty())
{
JOptionPane.showMessageDialog(null, "Provide a security deposit amomunnt");
} 
else 
{
try
{ Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sandeep","root","sandi");
Statement stmt= (Statement) con.createStatement();
String Query="INSERT INTO booking VALUES('"+name+"', '"+age+"', '"+gender+"', '"+persons+"', '"+mobile+"', '"+roomtype+"', '"+rooms+"', '"+checkin+"', '"+checkout+"', '"+sec+"');";
Stmt.executeUpdate(Query);
JOptionPane.showMessageDialog(this, "Thank you!\nYour booking has been successfully made");
} 
        catch (Exception e) 
{
JOptionPane.showMessageDialog(this, e.getMessage());
}
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
menue M=new menue();
M.setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox cb_rooms;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton rb_ac;
    private javax.swing.JRadioButton rb_d;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JRadioButton rb_nac;
    private javax.swing.JTextField tf_age;
    private javax.swing.JTextField tf_checkin;
    private javax.swing.JTextField tf_checkout;
    private javax.swing.JTextField tf_mobile;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_persons;
    private javax.swing.JTextField tf_security;
    // End of variables declaration//GEN-END:variables

    private void If(boolean selected) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
